import React, { Component } from "react";
import { Container, Row, Col, Image } from "react-bootstrap";

class FamilyRoom extends Component {
  render() {
    return (
      <Container>
        <Row>
          <Col xs="5" sm="5">
            <Image src="/assets/familyroom_1.png" thumbnail />
          </Col>
          <Col xs="7" sm="7">
            <p>
              The family room is to the right as you walk into the entryway.
              French double doors provide access to the patio.
            </p>
          </Col>
        </Row>
        <Row>
          <Col xs="5" sm="5">
            <Image src="/assets/familyroom_2.png" thumbnail />
          </Col>
          <Col xs="7" sm="7">
            <p>
              The entertainment center sits in the corner to the left of the
              fireplace. It is fed by a 300 channel Smart TV and 50Mbit Fiber
              Optic data connection. The center cabinet has two sliding doors.
              We request you leave the right hand door ALWAYS open to dissipate
              the heat generated by the components.
            </p>
            <p>
              The following components are present and operative:
              <ul>
                <li>
                  Yamaha Receiver - drives all the sound for all other
                  components.
                </li>
                <li>
                  The receiver feeds a 5.1 surround sound system in THX mode.
                </li>
                <li>
                  Apple TV (4th Gen) - used for streaming Netflix, Amazon Prime
                  and listening to Pandora Radio primarily.
                </li>
                <li>A Sony DVD player for watching movies.</li>
                <li>An HP Laserprinter in the left of the cabinet.</li>
              </ul>
            </p>
          </Col>
        </Row>
        <Row>
          <Col xs="5" sm="5">
            <Image src="/assets/familyroom_3.png" thumbnail />
          </Col>
          <Col xs="7" sm="7">
            <p>
              This is where we hang out generally when indoors. With an increase
              in home exchange activity, we added the standard TV channel
              package to a line-up of mostly streaming video including NetFlix
              and Amazon Prime. Both applications are run from within Apple TV.
              Standard TV includes 300 channels. To see the channels in HD,
              elect a channel number 1000 + the number of the channel you would
              like to watch. The TV is mounted above the mantle at a slight
              angle to make it easier to view from the other end of the room.
              However, if you grab the bottom of the TV and pull it forward, it
              will come out and down. When finished, just grab it at the bottom
              front, pushing slightly backwards and upwards at the same time
              (doing it with both hands makes it easier.) Quirk - the
              entertainment controller (Logitech device) is notoriously slow
              (very slow) - patience is key. If you printed something, move both
              doors to the right, then move them back. The controller itself has
              a number of buttons that have icons on them that have icons on
              them pointing to a task - Music (which will only play internet
              music from the receiver); Watch a Movie will switch the Sony
              CD/DVD player on and the TV screen should turn blue (ready to
              insert a DVD); Watch TV will switch to the local ATT U-verse feed
              for any of the TV stations you would like to watch; the 'More
              Activities' button activates the small color screen on the
              controller with 2 activities per page, use the left or right arrow
              button just below the screen to navigate through the pages. Within
              the "Use Apple TV" selection, we are signed up for Pandora,
              Netflix and Amazon Prime. Feel free to add any of your favorite
              Pandora Stations to listen to.
            </p>
            <p>
              The fireplace is gas-based with artificial logs. You don't need to
              open the valve. You will see the pilot light on, at the right
              behind the fire screen. The small covered device to the right of
              the logs is the ignitor/controlller of the gas logs. The fire
              screen is heavy, tilt it forward to get access to the valve and
              turn the knob counter clockwise to turn up the fire. You will feel
              some resistance when turning the knob, and hear each click as the
              fire gets higher and higher. When done, turn the knob all the way
              back clockwise until you cannot go any further - the fire will
              subside and no gas will be supplied. If tilting the screen forward
              does not work for you, just remove the screen, be careful, because
              it is heavy, put it back when the fire is going.
            </p>
          </Col>
        </Row>
        <Row>
          <Col xs="5" sm="5">
            <Image src="/assets/familyroom_4.png" thumbnail />
          </Col>
          <Col xs="7" sm="7" />
        </Row>
      </Container>
    );
  }
}

export default FamilyRoom;
