import React, { Component } from "react";
import { Grid, Row, Col, Image } from "react-bootstrap";

class FamilyRoom extends Component {
  render() {
    return (
      <Grid>
        <Row>
          <Col xs="5" sm="5">
            <Image src="/assets/familyroom_1.png" thumbnail />
          </Col>
          <Col xs="7" sm="7">
            <p>
              The family room is to the right as you walk into the hallway.
              French double door provide access to the patio.
            </p>
          </Col>
        </Row>
        <Row>
          <Col xs="5" sm="5">
            <Image src="/assets/familyroom_2.png" thumbnail />
          </Col>
          <Col xs="7" sm="7">
            <p>
              The entertainment center sits in the corner to the left of the
              fireplace. It is fed by a 300 channel TV and 50Mbit Fiber Optic
              data connection. The center cabinet has two sliding doors. We
              request you leave the right hand door ALWAYS open so the heat
              generated by the components can dissipate.
            </p>
            <p>
              The following components are present and operative:
              <ul>
                <li>Yamaha Receiver - drives all the sound for all other components</li>
                <li>Apple TV (4th Gen) - used for streaming Netflix, Amazon Prime and listening to Pandora Radio primarily</li>
                <li>A Sony DVD player for watching movies</li>
                <li>An HP Laserprinter in the left of the cabinet</li>
              </ul>
            </p>
          </Col>
        </Row>
        <Row>
          <Col xs="5" sm="5">
            <Image src="/assets/familyroom_3.png" thumbnail />

          </Col>
          <Col xs="7" sm="7">
            <p />
          </Col>
        </Row>
        <Row>
          <Col xs="5" sm="5">
            <Image src="/assets/familyroom_4.png" thumbnail />
          </Col>
          <Col xs="7" sm="7">
            <p />
          </Col>
        </Row>
      </Grid>
    );
  }
}

export default FamilyRoom;
